mblog/config/routes.rb
Rails.application.routes.draw do
  resources :mlogs
  get "mlogs/article", to: "pages#article"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

mblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

mblog/app/models/mlog.rb
class Mlog < ApplicationRecord
end

mblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

mblog/app/controllers/mlogs_controller.rb
class MlogsController < ApplicationController
  def index
    @mlogs = Mlog.all
  end

  def new
    @mlog = Mlog.new
  end

  def create
    @mlog = Mlog.new(mlog_params)
    if @mlog.save
      redirect_to mlogs_path, notice: "Mlog was successfully created."
    else
      render :new
    end
  end

  def show
    @mlog = Mlog.find(params[:id])
  end

  def edit
    @mlog = Mlog.find(params[:id])
  end

  def update
    @mlog = Mlog.find(params[:id])
    if @mlog.update(mlog_params)
      redirect_to mlogs_path, notice: "Mlog was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @mlog = Mlog.find(params[:id])
    @mlog.destroy
    redirect_to mlogs_path, notice: "Mlog was successfully destroyed."
  end

  private

  def mlog_params
    params.require(:mlog).permit(:title, :description, :content, :tags)
  end
end

mblog/app/helpers/application_helper.rb
module ApplicationHelper
end

mblog/app/helpers/mblogs1_helper.rb
module Mblogs1Helper
end

mblog/app/helpers/mlogs_helper.rb
module MlogsHelper
end

mblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mblog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,200..900;1,200..900&family=Titillium+Web&display=swap" rel="stylesheet">

  </head>
  <%# 不使用なら消す %>
  <%# <header>
    <nav class="navbar">
      <div class="container">
        <a class="title titillium-web-regular" href="/">conduit</a>
        <ul class="menu">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="/users/sign_in">Sign in</a>
            <a class="nav-link" href="/users/sign_up">Sign up</a>
        </ul>
      </div>
    </nav>
  </header> %>
  <body>
    <%= yield %>
  </body>
</html>

mblog/app/views/mlogs/create.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <ul class="error-messages">
          <li>That title is required</li>
        </ul>

        <form>
          <fieldset>
            <fieldset class="form-group">
              <input type="text" class="form-control form-control-lg" placeholder="Article Title" />
            </fieldset>
            <fieldset class="form-group">
              <input type="text" class="form-control" placeholder="What's this article about?" />
            </fieldset>
            <fieldset class="form-group">
              <textarea
                class="form-control"
                rows="8"
                placeholder="Write your article (in markdown)"
              ></textarea>
            </fieldset>
            <fieldset class="form-group">
              <input type="text" class="form-control" placeholder="Enter tags" />
              <div class="tag-list">
                <span class="tag-default tag-pill"> <i class="ion-close-round"></i> tag </span>
              </div>
            </fieldset>
            <button class="btn btn-lg pull-xs-right btn-primary" type="button">
              Publish Article
            </button>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

mblog/app/views/mlogs/edit.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <%= form_with model: @mlog, local: true do |form| %>
          <fieldset>
            <fieldset class="form-group">
              <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_field :description, class: "form-control", placeholder: "What's this article about?" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_area :content, class: "form-control", rows: 8, placeholder: "Write your article (in markdown)" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_field :tags, class: "form-control", placeholder: "Enter tags" %>
              <div class="tag-list">
                <span class="tag-default tag-pill">
                  <i class="ion-close-round"></i> tag
                </span>
              </div>
            </fieldset>
            <%= button_tag type: "submit", class: "btn btn-lg pull-xs-right btn-primary" do %>
              <i class="ion-save"></i> Publish Article
            <% end %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

mblog/app/views/mlogs/index.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row flex-container">
      <div class="col-md-9 left-content">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>
        <% @mlogs.each do |mlog| %>
          <div class="article-preview">
            <%= link_to mlog_path(mlog), class: "preview-link" do %>
              <h1><%= mlog.title %></h1>
              <p><%= mlog.description %></p>
              <div class="tuika-flex">
          <span>Read more...</span>

              </div>
            <% end %>
            <ul class="tag-list">
              <% mlog.tags.split(',').each do |tag| %>
          <li class="tag-default tag-pill tag-outline"><%= tag.strip %></li>
              <% end %>
            </ul>
          </div>
        <% end %>




        <div class="publish-article-button">
          <button class="btn btn-lg pull-xs-right btn-primary" type="button" onclick="location.href='/mlogs/new'">
            Create Article
          </button>
        </div>

      </div>

      <div class="col-md-3 right-content">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <a href="" class="tag-pill tag-default">programming</a>
            <a href="" class="tag-pill tag-default">javascript</a>
            <a href="" class="tag-pill tag-default">emberjs</a>
            <a href="" class="tag-pill tag-default">angularjs</a>
            <a href="" class="tag-pill tag-default">react</a>
            <a href="" class="tag-pill tag-default">mean</a>
            <a href="" class="tag-pill tag-default">node</a>
            <a href="" class="tag-pill tag-default">rails</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

mblog/app/views/mlogs/new.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <ul class="error-messages">
          <h1></h1>
        </ul>
        <%= form_with model: @mlog, local: true do |form| %>
          <fieldset>
            <fieldset class="form-group">
              <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_field :description, class: "form-control", placeholder: "What's this article about?" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_area :content, class: "form-control", rows: 8, placeholder: "Write your article (in markdown)" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_field :tags, class: "form-control", placeholder: "Enter tags" %>

            </fieldset>
            <%= button_tag "Publish Article", type: "submit", class: "btn btn-lg pull-xs-right btn-primary" %>
          </fieldset>
        <% end %>

      </div>
    </div>
  </div>
</div>

mblog/app/views/mlogs/show.html.erb
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @mlog.title %></h1>

      <div class="article-meta">
        <%# 削除リンク %>
        <%= link_to 'Edit Article', edit_mlog_path(@mlog), class: "btn btn-sm btn-outline-secondary" %>
        <%= button_to "Delete Article", mlog_path(@mlog), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <%# 記事本文　タイトルのぞく %>
        <p>
          <%= @mlog.description %>
        </p>
        <p>
          <%= @mlog.content %>
        </p>
        <%# <タグの一覧（@mlog.tags はカンマ区切りの文字列と仮定） %>
        <ul class="tag-list">
          <% @mlog.tags.split(',').each do |tag| %>
            <li class="tag-default tag-pill tag-outline"><%= tag.strip %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>